=== EroSDEV/1dam/Lenguajes de marcas/UT1/Actividad3.dtd
<!ELEMENT Alumnos (Alumno+)>
<!ELEMENT Alumno (Nombre, Apellido1, Apellido2, Edad, Modulos+, Cursos+)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Apellido1 (#PCDATA)>
<!ELEMENT Apellido2 (#PCDATA)>
<!ELEMENT Edad (#PCDATA)>
<!ELEMENT Modulos (Modulo+)>
<!ELEMENT Modulo (#PCDATA)>
<!ELEMENT Cursos (Curso+)>
<!ELEMENT Curso (#PCDATA)>
<!ATTLIST Alumno id CDATA #REQUIRED>

=== EroSDEV/1dam/Lenguajes de marcas/UT1/Actividad3.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE Alumnos SYSTEM "Actividad3.dtd">

<Alumnos>
    <Alumno id="1">
        <Nombre>Pepe</Nombre>
        <Apellido1>Pérez</Apellido1>
        <Apellido2>Rodríguez</Apellido2>
        <Edad>33</Edad>
        <Modulos>
            <Modulo>LND</Modulo>
            <Modulo>LNT</Modulo>
            <Modulo>FOL</Modulo>
            <Modulo>PRO</Modulo>
            <Modulo>ETS</Modulo>
            <Modulo>GTB</Modulo>
            <Modulo>SSF</Modulo>
        </Modulos>
        <Cursos>
            <Curso>2010</Curso>
            <Curso>2011</Curso>
            <Curso>2012</Curso>
        </Cursos>
    </Alumno>
</Alumnos>
